env:
  browser: true
  es6: true
extends: 'eslint:recommended'
globals:
  define: true
  module: true
rules:
  indent:
    - error
    - 2
    - VariableDeclarator: 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
